{% set name = "pyscenic" %}
{% set version = "0.12.1" %}
{% set sha256 = "ae8fafa707d2578ffe08f9eed85f14a4cd9e1b53d57217420e2e956f0a8ddba2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  - url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
    sha256: {{ sha256 }}
    folder: pyscenic-0.12.1
  - url: "https://files.pythonhosted.org/packages/source/a/arboreto/arboreto-0.1.6.tar.gz"
    sha256: 32fdac5e8a3e0ef2e196b5827f067d815ac4e689d2fca0dc437f42abdeeb89ab
    folder: arboreto-0.1.6
  - url: "https://files.pythonhosted.org/packages/source/i/interlap/interlap-0.2.7.tar.gz"
    sha256: 31e4f30c54b067c4939049f5d8131ae5e2fa682ec71aa56f89c0e5b900806ec9
    folder: interlap-0.2.7
  - url: "https://files.pythonhosted.org/packages/source/m/multiprocessing_on_dill/multiprocessing_on_dill-3.5.0a4.tar.gz"
    sha256: d6d50c300ff4bd408bb71eb78725e60231039ee9b3d0d9bb7697b9d0e15045e7
    folder: multiprocessing_on_dill-3.5.0a4
  - url: "https://github.com/aertslab/ctxcore/archive/refs/tags/0.2.0.tar.gz"
    sha256: a7ebf0f2625641b76a390993e12042e92fff7d0ac242c7fad5e3bff3ff3cd67a
    folder: ctxcore-0.2.0

build:
  number: 0
  run_exports:
    - {{ pin_subpackage(name, max_pin="x.x") }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make
    - python
    - pip
    - setuptools
    - wheel

  host:
    - python
    - pip
    - setuptools
    - wheel

  run:
    - python
    - aiohttp
    - attrs
    - boltons
    - cloudpickle
    - cytoolz
    - dask
    - distributed
    - frozendict
    - fsspec
    - llvmlite
    - loompy
    - networkx
    - numba >=0.51.2
    - numexpr
    - numpy
    - pandas >=1.3.5
    - pyyaml
    - requests
    - scikit-learn >=0.22.2
    - scipy
    - tqdm
    - umap-learn

test:
  imports:
    - pyscenic
    - pyscenic.cli
  commands:
    - pyscenic --help

about:
  home: "https://github.com/aertslab/pySCENIC"
  license: "GNU General Public v3 or later (GPLv3+)"
  license_family: GPL3
  license_file: "LICENSE"
  summary: "Python implementation of the SCENIC pipeline."
  description: |
    pySCENIC is a Python implementation of the SCENIC pipeline for transcription factor inference from single-cell transcriptomics experiments.

extra:
  recipe-maintainers:
    - 179018299
