{% set name = "pyscenic" %}
{% set version = "0.12.1" %}
{% set sha256 = "ae8fafa707d2578ffe08f9eed85f14a4cd9e1b53d57217420e2e956f0a8ddba2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: {{ sha256 }}

build:
  number: 0
  run_exports:
    - {{ pin_subpackage(name, max_pin="x.x") }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make
    - python
    - pip
    - setuptools
    - wheel

  host:
    - python
    - pip
    - setuptools
    - wheel

  run:
    - python
    - aiohttp
    - arboreto >=0.1.6
    - attrs
    - boltons
    - cloudpickle
    - ctxcore >=0.2.0
    - cytoolz
    - dask
    - distributed
    - frozendict
    - fsspec
    - interlap
    - llvmlite
    - loompy
    - multiprocessing_on_dill
    - networkx
    - numba >=0.51.2
    - numexpr
    - numpy
    - pandas >=1.3.5
    - pyyaml
    - requests
    - scikit-learn >=0.22.2
    - scipy
    - tqdm
    - umap-learn

test:
  imports:
    - pyscenic
    - pyscenic.cli
  commands:
    - pyscenic --help

about:
  home: "https://github.com/aertslab/pySCENIC"
  license: "GNU General Public v3 or later (GPLv3+)"
  license_family: GPL3
  license_file: "LICENSE"
  summary: "Python implementation of the SCENIC pipeline."
  description: |
    pySCENIC is a Python implementation of the SCENIC pipeline for transcription factor inference from single-cell transcriptomics experiments.
