{% set name = "pyscenic" %}
{% set version = "0.12.1" %}
{% set sha256 = "ae8fafa707d2578ffe08f9eed85f14a4cd9e1b53d57217420e2e956f0a8ddba2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  - url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
    sha256: "{{ sha256 }}"
    folder: pyscenic-0.12.1

build:
  number: 0
  run_exports:
    - "{{ pin_subpackage(name, max_pin='x.x') }}"

requirements:
  build:
    - "{{ compiler('c') }}"
    - "{{ compiler('cxx') }}"
    - make
    - python >=3.10,<3.11
    - pip
    - setuptools
    - wheel
    - setuptools_scm

  host:
    - python >=3.10,<3.11
    - pip
    - setuptools
    - wheel

  run:
    - python >=3.10,<3.11
    - aiohttp
    - arboreto 
    - attrs
    - boltons
    - cloudpickle
    - cytoolz
    - dill  
    - dask >=2023.4.1
    - distributed >=2023.4.1,<2023.5.0
    - frozendict
    - fsspec
    - llvmlite
    - loompy
    - networkx
    - numba >=0.51.2
    - numexpr
    - pandas >=1.3.5
    - pyyaml
    - requests
    - scikit-learn
    - scipy
    - tqdm
    - umap-learn
    - numpy ==1.23.5
    - pyarrow
    - interlap  
    - ctxcore  

test:
  imports:
    - pyscenic

about:
  home: https://github.com/aertslab/pySCENIC
  summary: 'pySCENIC is a python implementation of the SCENIC pipeline'
  license: MIT
  license_family: MIT
